image: vioneta/{arch}-hassio-cli
shadow_repository: ghcr.io/vioneta
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
args:
  CLI_VERSION: 4.23.0
  RLWRAP_VERSION: 0.45.2
labels:
  io.hass.type: cli
  org.opencontainers.image.title: VionetaOS CLI Plugin
  org.opencontainers.image.description: VionetaOS Supervisor plugin for CLI
  org.opencontainers.image.source: https://github.com/Vioneta/plugin-cli
  org.opencontainers.image.authors: The VionetaOS Authors
  org.opencontainers.image.url: https://www.vioneta.io/
  org.opencontainers.image.documentation: https://www.vioneta.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
